=== sandipnpatil/branch_cash_tally_tiaa_test/src/main/xsd/BranchDataFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/branchDataFile" xmlns:tns="http://www.example.org/branchDataFile" elementFormDefault="qualified">



    <complexType name="branchType">
    	<sequence>
    		<element name="location" type="string"></element>
    		<element name="totalCollection" type="string"></element>
    		<element name="locationId" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="orderDetailType">
    	<sequence>
    		<element name="orderid" type="byte"></element>
    		<element name="billamount" type="float"></element>
    	</sequence>
    </complexType>

    <complexType name="ordersType">
    	<sequence>
    		<element name="orderdetail" type="tns:orderDetailType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="cmFoodChainType">
    	<sequence>
    		<element name="branch" type="tns:branchType"></element>
    		<element name="orders" type="tns:ordersType"></element>
    	</sequence>
    </complexType>

    <element name="cmfoodchain" type="tns:cmFoodChainType"></element>
</schema>

=== sandipnpatil/branch_cash_tally_tiaa_test/src/main/resources/input/BOM-789-101.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:cmfoodchain xmlns:tns="http://www.example.org/branchDataFile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/branchDataFile BranchDataFile.xsd ">
  <tns:branch>
    <tns:location>"Mumbai"</tns:location>
    <tns:totalCollection>124.00</tns:totalCollection>
    <tns:locationId>BOM-789-101</tns:locationId>
  </tns:branch>
  <tns:orders>
  	<tns:orderdetail>
			<tns:orderid>1</tns:orderid>
			<tns:billamount>62.00</tns:billamount>
		</tns:orderdetail>
		<tns:orderdetail>
			<tns:orderid>2</tns:orderid>
			<tns:billamount>70.00</tns:billamount>
		</tns:orderdetail>

  </tns:orders>
</tns:cmfoodchain>
